### ISSUE TITLE
i get an error when i want to give the vehicle with the givecarkeys command i will take a look when i have the time but just so you know

### ISSUE THREAD

**Issue by Chang-nl** [zLeqitEclipse/esx_givecarkeys#1]
![image](https://user-images.githubusercontent.com/73784959/115414760-9c39ea00-a1f6-11eb-9a7d-ea6d5e08175d.png)

**Comment by zLeqitEclipse** [comment]
Looks like in you database that the plate cloumn is null or empty. Can you send me a screenshot of the `owned_vehicles` table from you database?

**Comment by TonySonta** [comment]
Hello, same error. Looks like the script needs to be able to also modify the vehicle column which also contains the plate

**Comment by TonySonta** [comment]
![image](https://user-images.githubusercontent.com/63284284/116267080-5e9c0a80-a77c-11eb-8980-223fb60635ba.png)

**Comment by TonySonta** [comment]
![image](https://user-images.githubusercontent.com/63284284/116267151-707dad80-a77c-11eb-845b-a78543d6e71f.png)

**Comment by TonySonta** [comment]
![image](https://user-images.githubusercontent.com/63284284/116300154-da0eb380-a79e-11eb-8c84-fe70cfbf0c4e.png)
